### ISSUE TITLE
Support pathlib2

### ISSUE THREAD

**Issue by sk-** [jmcgeheeiv/pyfakefs#408]
First of all thanks for this project, it's really useful. However, it'd be great if there was support for [`pathlib2`](https://github.com/mcmtroffaes/pathlib2).

In my code I'm importing it as `import pathlib2 as pathlib`. Which gets patched by `pyfakefs`, however the patch uses the system `pathlib`, which means that in my case it only works for Python 3.5 and 3.6, as I'm using the `exist_ok` argument of `mkdir`. In Python 3.4 I get the following error:

```
TypeError: mkdir() got an unexpected keyword argument 'exist_ok' 
```

And in Python 2.7 the module is not patched at all.

I already managed to get this to work in Python 2.7 (and probably in 3.4),

In my test I had to add

```py
def setUp():
  from pyfakefs import fake_pathlib
  self.modules_to_patch = {'pathlib': fake_pathlib.FakePathlibModule}
  self.setUpPyfakefs()
```

and I had to change `fake_pathlib.py` as following
```py
try:
  import pathlib2 as pathlib
except ImportError:
  import pathlib
try:
  from urllib.parse import quote_from_bytes as urlquote_from_bytes
except ImportError:
  from urllib import quote as urlquote_from_bytes
```

Let me know if you would be interested in accepting this change, so I could prepare a patch.

**Comment by mrbean-bremen** [comment]
Sure, that sounds helpful. I actually wasn't aware of `pathlib2`, but we did something similar with the `scandir` module which is a backport of 'scandir` to Python < 3.5.
And nice to know that the `modules_to_patch` has been used by someone :)

**Comment by matthew16550** [comment]
There is another difficulty using `pathlib2` with Python 2.7, the version checking in `FakePath.resolve()` prevents using `strict=False`.

e.g.
```python
def test_resolve(fs):
    Path('foo').resolve(False)
```

Causes:
 `TypeError: resolve() got an unexpected keyword argument 'strict'`

**Comment by mrbean-bremen** [comment]
Yes, the version checking has been made for `pathlib` only - the checks have to be changed for `pathlib2` support.
@sk- - are you still working on the PR? Do you need help?

**Comment by sk-** [comment]
@mrbean-bremen sorry I don't have the time to prepare the PR. Feel free to use any of the code snippets if they are of any help.

**Comment by matthew16550** [comment]
@mrbean-bremen I probably have time this weekend if you would like me to make a PR?

**Comment by mrbean-bremen** [comment]
@sk- no problem, thanks!
@matthew16550 - thanks for the offer - sure, we always welcome contributions! If you've got the time, please go ahead!

**Comment by mrbean-bremen** [comment]
Implemented in #422.
Thanks for your contribution and your patience!
